"""Post comments on GitHub PRs."""

import os
import sys
from datetime import datetime, timezone
from pathlib import Path

import httpx

GITHUB_API = "https://api.github.com"


def _today() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d")


def post_pr_comment(report_type: str) -> None:
    """Post a report as a PR comment, or update the old comment if no new report exists.

    Args:
        report_type: Either 'consistency_report' or 'review_report'.
    """
    token = os.environ.get("GITHUB_TOKEN")
    repo = os.environ.get("REPO")
    pr_number = os.environ.get("PR_NUMBER")

    if not all([token, repo, pr_number]):
        print("Missing required environment variables: GITHUB_TOKEN, REPO, PR_NUMBER")
        sys.exit(1)

    marker = f"<!-- doc-automation:{report_type} -->"
    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }

    report_path = Path(f".github/scripts/{report_type}.md")
    has_report = report_path.exists() and report_path.read_text().strip()

    if has_report:
        body = f"{marker}\n{report_path.read_text()}"
    else:
        # No report means the check passed cleanly — update the old comment
        body = (
            f"{marker}\n"
            "## Documentation-Code Consistency Report\n\n"
            "Result: **\u2705 PASSED** \u2014 no issues found\n\n"
            "All documentation is consistent with the codebase.\n\n"
            f"*Generated by documentation-code consistency check \u00b7 {_today()}*\n"
        )

    # Delete all existing comments from previous runs
    existing_ids = find_existing_comment(repo, pr_number, marker, headers)
    for comment_id in existing_ids:
        url = f"{GITHUB_API}/repos/{repo}/issues/comments/{comment_id}"
        with httpx.Client(timeout=30) as client:
            response = client.delete(url, headers=headers)
            response.raise_for_status()
        print(f"Deleted old PR comment #{comment_id}")

    # Create new comment
    url = f"{GITHUB_API}/repos/{repo}/issues/{pr_number}/comments"
    with httpx.Client(timeout=30) as client:
        response = client.post(url, headers=headers, json={"body": body})
        response.raise_for_status()
    print(f"Created new PR comment on #{pr_number}")


def find_existing_comment(repo: str, pr_number: str, marker: str, headers: dict) -> list[int]:
    """Find existing comments matching our marker or report title.

    Returns all matching comment IDs (marker-based first, then title-based fallback).
    """
    url = f"{GITHUB_API}/repos/{repo}/issues/{pr_number}/comments"

    with httpx.Client(timeout=30) as client:
        response = client.get(url, headers=headers, params={"per_page": 100})
        response.raise_for_status()

    # Title fallback catches comments posted by claude-code-action (no marker)
    title_pattern = "Documentation-Code Consistency Report"
    comment_ids = []
    for comment in response.json():
        body = comment.get("body", "")
        if marker in body or title_pattern in body:
            comment_ids.append(comment["id"])

    return comment_ids


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python github_pr.py <report_type>")
        print("  report_type: 'consistency_report' or 'review_report'")
        sys.exit(1)

    post_pr_comment(sys.argv[1])
