sonar.projectKey=isbn-db
sonar.projectName=ISBN Database
sonar.sources=src
sonar.tests=tests
sonar.python.version=3.13
sonar.sourceEncoding=UTF-8
sonar.exclusions=data/**,docs/report.html,**/__pycache__/**
