"""ISBN registration-area derivation.

The ISBN-13 registration group (the digits after the 978/979 EAN prefix) identifies the country or
language area that issued the ISBN — **independent of which data source supplied the record**. That
makes it the right basis for country/language analysis that isn't skewed by source coverage.

Mapping comes from the International ISBN Agency's official RangeMessage (``data/isbn_groups.json``,
regenerated by ``scripts/build_isbn_groups.py``). Groups are variable length (1-5 digits), so we
match the *longest* prefix. Note an area can be a language area spanning countries — ``978-0``/
``978-1`` = "English language", ``978-3`` = "German language" — or a single country (``978-91`` =
"Sweden", ``979-8`` = "United States").
"""

from __future__ import annotations

import json
from functools import lru_cache
from importlib.resources import files

import pycountry

from .db import connect

_GROUPS: dict[str, str] = json.loads(files("isbn_db").joinpath("data", "isbn_groups.json").read_text(encoding="utf-8"))
_MIN_LEN = min((len(k) for k in _GROUPS), default=4)
_MAX_LEN = max((len(k) for k in _GROUPS), default=8)


def registration_area(isbn13: str) -> str | None:
    """Country/language area for an ISBN-13, by longest matching registration-group prefix."""
    for length in range(_MAX_LEN, _MIN_LEN - 1, -1):
        area = _GROUPS.get(isbn13[:length])
        if area:
            return area
    return None


@lru_cache(maxsize=1)
def build_area_case_sql(column: str = "isbn13") -> str:
    """SQL CASE expression mapping ``column`` to its registration area (longest prefix wins).

    Branches are emitted longest-prefix-first so the first match in the CASE is the correct one.
    """
    branches = sorted(_GROUPS.items(), key=lambda kv: -len(kv[0]))
    whens = [
        f"WHEN left({column}, {len(prefix)}) = '{prefix}' THEN '{area.replace(chr(39), chr(39) * 2)}'"
        for prefix, area in branches
    ]
    return "CASE " + " ".join(whens) + " END"


def derive_all(*, batch: int = 1_000_000, redo: bool = False, log=print) -> int:
    """Populate ``registration_area`` for every row (derived purely from isbn13). Returns rows set.

    ``registration_area`` only depends on the immutable ISBN, so by default this fills rows where it
    is still NULL; pass ``redo`` to recompute all (e.g. after refreshing the group table).
    """
    case_sql = build_area_case_sql("isbn13")
    # The inner select must exclude rows whose prefix matches no group: their derived area is NULL,
    # so updating NULL -> NULL leaves them selectable forever and the loop never terminates. The
    # `({case_sql}) IS NOT NULL` guard skips those unknown-prefix rows (they stay permanently NULL).
    sql = (
        f"UPDATE editions SET registration_area = {case_sql} "
        "WHERE isbn13 IN (SELECT isbn13 FROM editions "
        f"WHERE registration_area IS NULL AND ({case_sql}) IS NOT NULL "
        "LIMIT %(batch)s FOR UPDATE SKIP LOCKED)"
    )
    total = 0
    with connect() as conn:
        conn.execute("ALTER TABLE editions ADD COLUMN IF NOT EXISTS registration_area TEXT")
        conn.commit()
        if redo:
            conn.execute("UPDATE editions SET registration_area = NULL")
            conn.commit()
        while True:
            n = conn.execute(sql, {"batch": batch}).rowcount
            conn.commit()
            if n == 0:
                break
            total += n
            log(f"[geo] derived area for {total:,} rows")
    return total


# --- Area classification ---------------------------------------------------------------------
#
# A registration_area is the ISBN agency's label, which is NOT always a single country. We classify
# each label deterministically so a UI can treat them correctly (e.g. never plot a language area on a
# single point, and offer a real per-country / map view only for `country` rows with an ISO code).

AREA_COUNTRY = "country"            # a single sovereign/territory with an ISO code
AREA_LANGUAGE = "language_area"     # spans multiple countries (English/German/French)
AREA_REGION = "region"             # multi-country geographic agency
AREA_HISTORICAL = "historical"     # superseded state still issuing under the old prefix
AREA_ADMIN = "administrative"      # reserved / supranational / non-geographic ranges

# Labels that are multi-country regions or non-geographic admin groups (cannot be inferred from text).
_REGION = {"Caribbean Community", "South Pacific"}
_ADMIN = {
    "Reserved Agency",
    "Federated Panel",
    "International NGO Publishers",
    "International NGO Publishers and EU Organizations",
}
# ISO 3166-1 alpha-2 for labels pycountry cannot resolve by name. None = no single ISO (sub-national).
_ISO_OVERRIDES: dict[str, str | None] = {
    "China, People's Republic": "CN",
    "Hong Kong, China": "HK",
    "Korea, P.D.R.": "KP",
    "Korea, Republic": "KR",
    "Kosova": "XK",
    "Macau": "MO",
    "Palestine": "PS",
    "Zambia registration group": "ZM",
    "Srpska, Republic of": None,  # entity within Bosnia and Herzegovina; no sovereign ISO code
}


@lru_cache(maxsize=512)
def classify_area(area: str | None) -> tuple[str | None, str | None]:
    """Deterministically map a registration area to ``(area_kind, country_iso2)``.

    ``country_iso2`` is populated only for single-country areas (``AREA_COUNTRY``); language areas,
    regions, historical states, and administrative ranges have no single ISO code.
    """
    if not area:
        return (None, None)
    if "language" in area.lower():
        return (AREA_LANGUAGE, None)
    if area.lower().startswith("former "):
        return (AREA_HISTORICAL, None)
    if area in _REGION:
        return (AREA_REGION, None)
    if area in _ADMIN:
        return (AREA_ADMIN, None)
    if area in _ISO_OVERRIDES:
        return (AREA_COUNTRY, _ISO_OVERRIDES[area])
    try:
        return (AREA_COUNTRY, pycountry.countries.lookup(area).alpha_2)
    except LookupError:
        return (AREA_COUNTRY, None)  # a country we couldn't ISO-resolve; still a single country


def is_single_country(area: str | None) -> bool:
    return classify_area(area)[0] == AREA_COUNTRY


def area_meta() -> dict[str, tuple[str | None, str | None]]:
    """Classification for every known agency label (the distinct values in the group table)."""
    return {label: classify_area(label) for label in set(_GROUPS.values())}


def classify_all(*, redo: bool = False, log=print) -> int:
    """Populate ``area_kind`` and ``country_iso2`` from ``registration_area``.

    Maintains a small ``isbn_area_meta`` dimension table (one row per agency label) and joins it to
    ``editions``. Deterministic and idempotent; safe to run alongside an active ingest.
    """
    total = 0
    with connect() as conn:
        conn.execute("ALTER TABLE editions ADD COLUMN IF NOT EXISTS area_kind TEXT")
        conn.execute("ALTER TABLE editions ADD COLUMN IF NOT EXISTS country_iso2 TEXT")
        conn.execute(
            "CREATE TABLE IF NOT EXISTS isbn_area_meta "
            "(registration_area TEXT PRIMARY KEY, area_kind TEXT, country_iso2 TEXT)"
        )
        conn.execute("CREATE INDEX IF NOT EXISTS editions_country_iso2_idx ON editions (country_iso2)")
        conn.commit()

        meta_rows = [(label, kind, iso) for label, (kind, iso) in area_meta().items()]
        with conn.cursor() as cur:
            cur.executemany(
                "INSERT INTO isbn_area_meta (registration_area, area_kind, country_iso2) VALUES (%s,%s,%s) "
                "ON CONFLICT (registration_area) DO UPDATE SET area_kind=EXCLUDED.area_kind, "
                "country_iso2=EXCLUDED.country_iso2",
                meta_rows,
            )
        conn.commit()
        if redo:
            conn.execute("UPDATE editions SET area_kind = NULL, country_iso2 = NULL")
            conn.commit()

        sql = (
            "UPDATE editions e SET area_kind = m.area_kind, country_iso2 = m.country_iso2 "
            "FROM isbn_area_meta m WHERE e.registration_area = m.registration_area AND e.isbn13 IN ("
            "SELECT isbn13 FROM editions WHERE registration_area IS NOT NULL AND area_kind IS NULL "
            "LIMIT %(batch)s FOR UPDATE SKIP LOCKED)"
        )
        while True:
            n = conn.execute(sql, {"batch": 1_000_000}).rowcount
            conn.commit()
            if n == 0:
                break
            total += n
            log(f"[geo] classified {total:,} rows")
    return total
