"""ISBN registration-area derivation.

The ISBN-13 registration group (the digits after the 978/979 EAN prefix) identifies the country or
language area that issued the ISBN — **independent of which data source supplied the record**. That
makes it the right basis for country/language analysis that isn't skewed by source coverage.

Mapping comes from the International ISBN Agency's official RangeMessage (``data/isbn_groups.json``,
regenerated by ``scripts/build_isbn_groups.py``). Groups are variable length (1-5 digits), so we
match the *longest* prefix. Note an area can be a language area spanning countries — ``978-0``/
``978-1`` = "English language", ``978-3`` = "German language" — or a single country (``978-91`` =
"Sweden", ``979-8`` = "United States").
"""

from __future__ import annotations

import json
from functools import lru_cache
from importlib.resources import files

from .db import connect

_GROUPS: dict[str, str] = json.loads(files("isbn_db").joinpath("data", "isbn_groups.json").read_text(encoding="utf-8"))
_MIN_LEN = min((len(k) for k in _GROUPS), default=4)
_MAX_LEN = max((len(k) for k in _GROUPS), default=8)


def registration_area(isbn13: str) -> str | None:
    """Country/language area for an ISBN-13, by longest matching registration-group prefix."""
    for length in range(_MAX_LEN, _MIN_LEN - 1, -1):
        area = _GROUPS.get(isbn13[:length])
        if area:
            return area
    return None


@lru_cache(maxsize=1)
def build_area_case_sql(column: str = "isbn13") -> str:
    """SQL CASE expression mapping ``column`` to its registration area (longest prefix wins).

    Branches are emitted longest-prefix-first so the first match in the CASE is the correct one.
    """
    branches = sorted(_GROUPS.items(), key=lambda kv: -len(kv[0]))
    whens = [
        f"WHEN left({column}, {len(prefix)}) = '{prefix}' THEN '{area.replace(chr(39), chr(39) * 2)}'"
        for prefix, area in branches
    ]
    return "CASE " + " ".join(whens) + " END"


def derive_all(*, batch: int = 1_000_000, redo: bool = False, log=print) -> int:
    """Populate ``registration_area`` for every row (derived purely from isbn13). Returns rows set.

    ``registration_area`` only depends on the immutable ISBN, so by default this fills rows where it
    is still NULL; pass ``redo`` to recompute all (e.g. after refreshing the group table).
    """
    case_sql = build_area_case_sql("isbn13")
    sql = (
        f"UPDATE editions SET registration_area = {case_sql} "
        "WHERE isbn13 IN (SELECT isbn13 FROM editions WHERE registration_area IS NULL "
        "LIMIT %(batch)s FOR UPDATE SKIP LOCKED)"
    )
    total = 0
    with connect() as conn:
        conn.execute("ALTER TABLE editions ADD COLUMN IF NOT EXISTS registration_area TEXT")
        conn.commit()
        if redo:
            conn.execute("UPDATE editions SET registration_area = NULL")
            conn.commit()
        while True:
            n = conn.execute(sql, {"batch": batch}).rowcount
            conn.commit()
            if n == 0:
                break
            total += n
            log(f"[geo] derived area for {total:,} rows")
    return total
